Improve readability of initialization phase

diff --git a/archx b/archx
--- a/archx
+++ b/archx
@@ -12,20 +12,35 @@
 #
 # / *************************************************************************** /
 
-# Retrive static file from the project repository - change these to your own repository if needed!
-_url="https://raw.githubusercontent.com/atirelli3/archx/refs/heads/main/static"
-_dirname=".archxtmp"  # Temporary directory for store support files of the script
+_static_uri=""        # URI of static file
+_dirname=".archxtmp"  # Temorary directory for store script's files
+
+# Note: URI of static file is set to the GitHub repository of the project - change this if needed!
+_static_uri="https://raw.githubusercontent.com/atirelli3/archx/refs/heads/main/static"
 
 mkdir -p "$_dirname"
-wget -q0 "$_dirname/static" "$_url" 2>/dev/null
-[ -f "$_dirname/static" ] || { echo "Failed to download static configuration file!"; exit 1; }
-source "$_dirname/static"  # Load the static variables necessary for the script
+wget -q0 "$_dirname/static" "$_static_uri"
 
-_machine_name=$1  # Name of the machine to configure, passed as the first argument
-_machine_url="${MACHINE_URL}/$_machine_name"  # URL to retrieve the machine configuration file
+if [ ! -f "$_dirname/static" ]; then
+    echo "Failed to download static configuration file!"
+    exit 1
+fi
+source "$_dirname/static"  # Load static variables
 
-[ -z "$_machine_name" ] && { echo "Usage: $0 <machine_name>"; exit 1; }
-wget -q0 "$_dirname/$_machine_name" "$_machine_url" 2>/dev/null
-[ -f "$_dirname/$_machine_name" ] || { echo "Failed to download machine configuration file!"; exit 1; }
-source "$_dirname/$_machine_name"  # Load the machine configuration file
+
+_machine=$1                              # Name of the machine to configure, passed as the first argument
+_machine_url="${MACHINE_URL}/$_machine"  # URL to retrieve the machine configuration file
+
+if [ -z "$_machine" ]; then
+    echo "Usage: $0 <machine_name>"
+    exit 1
+fi
+
+wget -q0 "$_dirname/$_machine" "$_machine_url"
+if [ ! -f "$_dirname/$_machine" ]; then
+    echo "Failed to download machine configuration file!"
+    exit 1
+fi
+source "$_dirname/$_machine"  # Load the machine configuration file, ready to start the ArchX script!
+
 # ------------------------------------------------------------------------------
